---
galaxy_info:
  author: Demo Project Author
  description: Project level demo role
  company: Demo
  license: MIT
  min_ansible_version: '2.9'
  platforms:
    - name: Ubuntu
      versions:
        - focal
dependencies: []
