---
# Webserver Role - Handlers

- name: Reload Nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  tags:
    - webserver

- name: Restart Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  tags:
    - webserver
